ecomstore/cart/urls.py
'''
Created on Jan 24, 2016

@author: wale
'''

from django.conf.urls import url,patterns
from . import views
urlpatterns = patterns('',
                       url(r'^$', views.show_cart, name='show_cart'),
                       )

ecomstore/catalog/urls.py
'''
Created on Jan 16, 2016

@author: wale
'''
from django.conf.urls import include, url,patterns
from . import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='catalog_home'),
                       url(r'^category/(?P<category_slug>[-\w]+)/$',
                        views.show_category, name='catalog_category'),
                       url(r'^category/(?P<category_slug>[-\w]+)/(?P<b_slug>[-\w]+)/$',
                        views.show_category_brands, name='category_brand'),
                       url(r'^product/(?P<product_slug>[-\w]+)/$',views.show_product,name='catalog_product'),
                       url(r'^review/product/add/$',views.add_review,name='add_review'),
                       url(r'^tag/product/add/$', views.add_tag,name='add_tag'),
                       url(r'^tag_cloud/$', views.tag_cloud,name='tag_cloud'),
                       url(r'^tag/(?P<tag>[-\w]+)/$', views.tag,name='tag'),
                       )

ecomstore/ecomstore/urls.py
from django.conf import settings
from django.conf.urls import url, include,handler404,handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


admin.autodiscover()
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('catalog.urls')),
    url(r'^cart/', include('cart.urls')),
    url(r'^account/', include('account.urls')),
    url(r'^account/', include('django.contrib.auth.urls')),
   url(r'^checkout/',include('checkout.urls')),
   url(r'^search/', include('search.urls')),
   url(r'^', include('marketing.urls')),
]
if settings.DEBUG: #checks if django project is being run in debug mode
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404='ecomstore.views.file_not_found_404'
handler500='ecomstore.views.internal_server_error_500'

ecomstore/catalog/models.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models

import tagging
from tagging.registry import register

from .myThumbs import ThumbnailImageField


# Create your models here.
GENDERS=(
        ('UX', 'unisex'),
        ('M', 'men'),
        ('F', 'Female'),
        )
class ActiveCategoryManager(models.Manager):
    def get_queryset(self):
        return super(ActiveCategoryManager, self).get_queryset().filter(is_active=True)

class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True,
                            help_text='Unique value for product page URL, created from name.')
    description = models.TextField()
    is_active = models.BooleanField(default=True)
    meta_keywords = models.CharField("Meta Keywords",max_length=255, help_text='Comma-delimited set of SEO keywords for meta tag')
    meta_description = models.CharField("Meta Description", max_length=255,
                                        help_text='Content for description meta tag')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    objects = models.Manager()
    active = ActiveCategoryManager()
    
    class Meta:
        db_table = 'categories'
        ordering = ['-created_at']
        verbose_name_plural = 'Categories'
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('catalog_category',args=[str(self.slug)])
    
# class ActiveBrandManager(models.Manager):
#     def get_queryset(self):
#         return super(ActiveCategoryManager, self).get_queryset().filter(is_active=True)
# 
# class Brand(models.Model):
#     name = models.CharField(max_length=50)
#     slug = models.SlugField(max_length=50, unique=True,
#                             help_text='Unique value for product page URL, created from name.')
#     description = models.TextField()
#     is_active = models.BooleanField(default=True)
#     meta_keywords = models.CharField("Meta Keywords",max_length=255, help_text='Comma-delimited set of SEO keywords for meta tag')
#     meta_description = models.CharField("Meta Description", max_length=255,
#                                         help_text='Content for description meta tag')
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)
#     
#     objects = models.Manager()
#     active = ActiveBrandManager()
#     
#     class Meta:
#         db_table = 'brands'
#         ordering = ['-created_at']
#         
#     def __str__(self):
#         return self.name
#     
#     def get_absolute_url(self):
#         return reverse('category_brand',args=[str(self.slug)])
        
class ActiveProductManager(models.Manager):
    #only the active records
    def get_queryset(self):
        return super(ActiveProductManager, self).get_queryset().filter(is_active=True)
    
class FeaturedProductManager(models.Manager):
    def all(self):
        return super(FeaturedProductManager, self).all().filter(is_active=True).filter(is_featured=True)
    

class Product(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True,
                            help_text='Unique value for product page URL, created from name.')
    
    brand = models.CharField(max_length=255,null=True)
    b_slug = models.SlugField(max_length=255,null=True)
    
    sku = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=9,decimal_places=2)
    old_price = models.DecimalField(max_digits=9,decimal_places=2,blank=True,default=0.00)
    #image = models.CharField(max_length=50)
    image =models.ImageField(upload_to='images/products/main')
    thumbnail = ThumbnailImageField(upload_to='images/products/thumbnails',thumb_width=125,thumb_height=125,default='')
    thumbnail1 = ThumbnailImageField(upload_to='images/products/thumbnails',thumb_width=125,thumb_height=125,null=True)
    thumbnail2 = ThumbnailImageField(upload_to='images/products/thumbnails',thumb_width=125,thumb_height=125,null=True)
    
    is_active = models.BooleanField(default=True)
    is_featured=models.BooleanField(default=False)
    
    gender=models.CharField(max_length=20,choices=GENDERS)
    
    quantity = models.IntegerField()
    description = models.TextField()
    meta_keywords = models.CharField(max_length=255,help_text='Comma-delimited set of SEO keywords for meta tag')
    meta_description = models.CharField(max_length=255,help_text='Content for description meta tag')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    categories = models.ManyToManyField(Category)
    
    objects = models.Manager()
    active = ActiveProductManager()
    featured=FeaturedProductManager()
    
    class Meta:
        db_table = 'products'
        ordering = ['-created_at']
        
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('catalog_product',args=[str(self.slug)])

    @property
    def sale_price(self):
        if self.old_price > self.price:
            return self.price
        else:
            return None
    
    #Order-Based Filtering    
    def cross_sell(self):
        from checkout.models import Order,OrderItem
        orders=Order.objects.filter(orderitem__product=self)#where product is in  orderitem.products
        order_items=OrderItem.objects.filter(order__in=orders).exclude(product=self)#get other items excluding the presect product in the same order
        products=Product.active.filter(orderitem__in=order_items).distinct() #get the active ones removing duplicates
        return products
    
    #Customer-Based Order Filtering
    def cross_sell_user(self):
        from checkout.models import Order,OrderItem
        from django.contrib.auth.models import User
        users=User.objects.filter(order__orderitem__product=self)#get the users who made the order
        items=OrderItem.objects.filter(order__user__in=users).exclude(product=self) #list of other items ordered by same user
        products = Product.active.filter(orderitem__in=items).distinct()
        return products
        
    def cross_sell_hybrid(self):
        from checkout.models import Order,OrderItem
        from django.contrib.auth.models import User
        from django.db.models import Q
        orders=Order.objects.filter(orderitem__product=self)
        users=User.objects.filter(order__orderitem__product=self)
        items=OrderItem.objects.filter(Q(order__in=orders)|Q(order__user__in=users)).exclude(product=self)
        products = Product.active.filter(orderitem__in=items).distinct()
        #print(products)
        return products

try:
    register(Product)
except tagging.registry.AlreadyRegistered:
    pass
    
class ActiveProductReviewManager(models.Manager):
    def all(self):
        return super(ActiveProductReviewManager, self).all().filter(is_approved=True)
    
class ProductReview(models.Model):
    RATINGS = ((5,5),(4,4),(3,3),(2,2),(1,1),)
    
    product=models.ForeignKey(Product)
    user=models.ForeignKey(User)
    title=models.CharField(max_length=50)
    date=models.DateTimeField(auto_now_add=True)
    rating=models.PositiveSmallIntegerField(default=5,choices=RATINGS)
    is_approved=models.BooleanField(default=True)
    content=models.TextField()
    
    objects=models.Manager()
    approved=ActiveProductReviewManager()
    

ecomstore/catalog/forms.py
'''
Created on Jan 16, 2016

@author: wale
'''
from django import forms

from catalog.models import ProductReview

from .models import Product


class ProductAdminForm(forms.ModelForm):
    class Meta:
        model =Product
        exclude=()
    
    def clean_price(self):
        if self.cleaned_data['price'] <= 0:
            raise forms.ValidationError('Price must be greater than zero.')
        return self.cleaned_data['price']
    
class ProductReviewForm(forms.ModelForm):
    class Meta:
        model = ProductReview
        exclude = ('user','product', 'is_approved')

ecomstore/tagging/views.py
"""
Tagging related views.
"""
from django.http import Http404
from django.views.generic.list import ListView
from django.utils.translation import ugettext as _
from django.core.exceptions import ImproperlyConfigured

from tagging.models import Tag
from tagging.models import TaggedItem
from tagging.utils import get_tag
from tagging.utils import get_queryset_and_model


class TaggedObjectList(ListView):
    """
    A thin wrapper around
    ``django.views.generic.list.ListView`` which creates a
    ``QuerySet`` containing instances of the given queryset or model
    tagged with the given tag.

    In addition to the context variables set up by ``object_list``, a
    ``tag`` context variable will contain the ``Tag`` instance for the
    tag.

    If ``related_tags`` is ``True``, a ``related_tags`` context variable
    will contain tags related to the given tag for the given model.
    Additionally, if ``related_tag_counts`` is ``True``, each related
    tag will have a ``count`` attribute indicating the number of items
    which have it in addition to the given tag.
    """
    tag = None
    related_tags = False
    related_tag_counts = True

    def get_tag(self):
        if self.tag is None:
            try:
                self.tag = self.kwargs.pop('tag')
            except KeyError:
                raise AttributeError(
                    _('TaggedObjectList must be called with a tag.'))

        tag_instance = get_tag(self.tag)
        if tag_instance is None:
            raise Http404(_('No Tag found matching "%s".') % self.tag)

        return tag_instance

    def get_queryset_or_model(self):
        if self.queryset is not None:
            return self.queryset
        elif self.model is not None:
            return self.model
        else:
            raise ImproperlyConfigured(
                "%(cls)s is missing a QuerySet. Define "
                "%(cls)s.model, %(cls)s.queryset, or override "
                "%(cls)s.get_queryset_or_model()." % {
                    'cls': self.__class__.__name__
                }
            )

    def get_queryset(self):
        self.queryset_or_model = self.get_queryset_or_model()
        self.tag_instance = self.get_tag()
        return TaggedItem.objects.get_by_model(
            self.queryset_or_model, self.tag_instance)

    def get_context_data(self, **kwargs):
        context = super(TaggedObjectList, self).get_context_data(**kwargs)
        context['tag'] = self.tag_instance

        if self.related_tags:
            queryset, model = get_queryset_and_model(self.queryset_or_model)
            context['related_tags'] = Tag.objects.related_for_model(
                self.tag_instance, model, counts=self.related_tag_counts)
        return context

ecomstore/templates/catalog/brand.html
{% extends "base.html" %}
{% load staticfiles %}
{% load catalog_tags %}
{% load catalog_filters %}
{% block extra_title %}{{ page_title }}{% endblock %}

{% block body_content %}
	<!-- START PRIMARY SECTION -->
	<div id="primary" class="inner group" />
	<div class="layout-sidebar-left group">
	   <div id="container">
	      <div id="content" role="main">
	         <div id="breadcrumb"><a class="home" href="home.html">Home</a>  &rsaquo; <a href="shop.html">Shop</a></div>
	         {% if p in products %}
	         <h1 class="page-title">All Products</h1>
	         {% else %}
	         <h1 class="page-title">No Products</h1>
	         {% endif %}
	         <h2></h2>
	         <ul class="products">
	         {% for p in products %}
	         {% if  forloop.count > 1 and forloop.first %}
	            <li class="product border shadow first">
	         {% endif %}
	         {% if forloop.last %}
	         	<li class="product border shadow last">
	         {% else %}
	         	<li class="product border shadow ">
	         {% endif %}
	               <a href="{{ p.get_absolute_url }}">
	                  {% include 'tags/product_thumbnail.html' %}
	                  <span class="price">{{ p.price|currency }}</span>		
	               </a>
	               <div class="buttons">
	                  <a href="{{ p.get_absolute_url }}" class="details">DETAILS</a>&nbsp;
	                  <form action="." class="cart" method="post">
					      {{ form.as_p }} {% csrf_token %}
					      <button type="submit" class="button-alt">Add to cart</button>		
					  </form>
	            </li>
	           {% endfor %}
	         </ul>
	         <div class="clear"></div>
	      </div>
	   </div>
	   <div id="sidebar" class="shop group">
	      <div id="product_categories-3" class="widget-1 widget-first widget widget_product_categories">
	         {% category_list request.path %}
	      </div>
	      <div id="product_categories-3" class="widget-1 widget-first widget widget_product_categories">
	          <h4>Brands</h4>
	         <ul lass="sub-menu">
	         	{% for p in products %}
				<li >
					<a class="btn btn-link" href=''>{{ p.brand }}</a>
				</li>
				{% endfor %}
			<ul>
	      </div>
	      <div id="text-image-3" class="widget-2 widget-last widget text-image">
	         <div class="text-image" style="text-align:left"><img src="images/free.jpg" alt="" /></div>
	      </div>
	   </div>
	</div>
	<!-- END PRIMARY SECTION -->
{% endblock %}

ecomstore/templates/catalog/category.html
{% extends "base.html" %}
{% load staticfiles %}
{% load catalog_tags %}
{% load catalog_filters %}
{% block extra_title %}{{ page_title }}{% endblock %}

{% block body_content %}
	<!-- START PRIMARY SECTION -->
	<div id="primary" class="inner group" />
	<div class="layout-sidebar-left group">
	   <div id="container">
	      <div id="content" role="main">
	         <div id="breadcrumb"><a class="home" href="home.html">Home</a>  &rsaquo; <a href="shop.html">Shop</a></div>
	         {% if p in products %}
	         <h1 class="page-title">All Products</h1>
	         {% else %}
	         <h1 class="page-title">No Products</h1>
	         {% endif %}
	         <h2></h2>
	         <ul class="products">
	         {% for p in products %}
	         {% if  forloop.count > 1 and forloop.first %}
	            <li class="product border shadow first">
	         {% endif %}
	         {% if forloop.last %}
	         	<li class="product border shadow last">
	         {% else %}
	         	<li class="product border shadow ">
	         {% endif %}
	               <a href="{{ p.get_absolute_url }}">
	                  {% include 'tags/product_thumbnail.html' %}
	                  <span class="price">{{ p.name }} {{ p.price|currency }}</span>		
	               </a>
	               <div class="buttons">
	                  <a href="{{ p.get_absolute_url }}" class="details">DETAILS</a>&nbsp;
	                  <form action="." class="cart" method="post">
					      {{ form.as_p }} {% csrf_token %}
					      <button type="submit" class="button-alt">Add to cart</button>		
					   </form>
	               </div>
	            </li>
	           {% endfor %}
	         </ul>
	         <div class="clear"></div>
	      </div>
	   </div>
	   <div id="sidebar" class="shop group">
	      <div id="product_categories-3" class="widget-1 widget-first widget widget_product_categories">
	         {% category_list request.path %}
	      </div>
	      <div id="product_categories-3" class="widget-1 widget-first widget widget_product_categories">
	         <h4>Brands</h4>
	         <ul lass="sub-menu">
	         	{% for p in products %}
				<li >
					<a class="btn btn-link" href=''>{{ p.brand }}</a>
				</li>
				{% endfor %}
			<ul>
	      </div>
	      <div id="text-image-3" class="widget-2 widget-last widget text-image">
	         <div class="text-image" style="text-align:left"><img src="images/free.jpg" alt="" /></div>
	      </div>
	   </div>
	</div>
	<!-- END PRIMARY SECTION -->
{% endblock %}

ecomstore/templates/catalog/index.html
{% extends "base.html"%}
{% load catalog_tags %}
    {% block extra_title %}{{ page_title }}{% endblock %}
    {% block body_content %}
    

    <div id="slider" class="group inner">
        <ul class="group">
            <li class="first slide-1 group image-content-type">
                <div class="slider-featured group"><a href="http://www.google.it"><img src="{{ MEDIA_URL }}css.css" width="960" height="338" alt="interior design" /></a></div>
                <div class="slider-caption caption-right">
                    <!-- TITLE -->
                    <h2><a href="http://www.google.it">interior design</a></h2>
                    <!-- TEXT -->
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pulvinar turpis velit. Morbi rutrum, neque non pulvinar faucibus, ligula eros viverra ligula, et aliquam libero neque ac nisl. </p>
                    <p><span class="special-font" style="font-size:24px;">prices from <span style="font-size:42px;">$45</span></span></p>
                </div>
            </li>
            <li class="slide-2 group image-content-type">
                <div class="slider-featured group"><img src="images/common/0035.jpg" width="960" height="338" alt="Luxury gold" /></div>
                <div class="slider-caption caption-right">
                    <!-- TITLE -->
                    <h2>Luxury gold</h2>
                    <!-- TEXT -->
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pulvinar turpis velit. Morbi rutrum, neque non pulvinar faucibus, ligula eros viverra ligula, et aliquam libero neque ac nisl. </p>
                </div>
            </li>
            <li class="last slide-3 group image-content-type">
                <div class="slider-featured group"><img src="images/common/0031.jpg" width="960" height="338" alt="Gold Parquet" /></div>
                <div class="slider-caption caption-right">
                    <!-- TITLE -->
                    <h2>Gold Parquet</h2>
                    <!-- TEXT -->
                    <p>The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum</p>
                    <p><span class="special-font" style="font-size:24px;">prices from <span style="font-size:42px;">$37</span></span></p>
                </div>
            </li>
        </ul>
    </div>
    <!-- END SLIDER -->            
    <div class="slider-mobile">
        <!-- START SLIDER -->
        <div id="slider" class="group mobile inner fixed-image">
            <img src="images/common/001.jpg" width="960" height="338" alt="" />  
        </div>
        <!-- END SLIDER -->
        <script type="text/javascript">      
            var 	yiw_slider_type = 'elegant',
                    yiw_slider_elegant_easing = null,
        		    yiw_slider_elegant_fx = 'fade',
        		    yiw_slider_elegant_speed = 500,
        		    yiw_slider_elegant_timeout = 5000,
        		    yiw_slider_elegant_caption_speed = 500;
        </script>
     
    </div>
    <!-- START PRIMARY SECTION -->
    <div id="primary" class="inner group">
        <div id="slogan" class="inner">
            <h1>Welcome to Sommerce, a nice and  fresh perspective to your e-commerce site</h1>
            <h3>unlimited layout styles by changing fonts, colors, backgrounds, images and sliders</h3>
        </div>
        <div class="layout-sidebar-no">
            <!-- START CONTENT -->
            <div id="content" role="main" class="group wrapper-content">
                <div id="post-7" class="post-7 page type-page status-publish hentry group">
                    <div class="boxed-content group">
                        {% product_list recently_viewed 'Your Recently Viewed' %}
                    </div>
                    <div class="boxed-content group">
                        {% product_list view_recs 'Similar Products' %}
                    </div>
                    <div class="boxed-content group">
                        {% product_list featured 'Featured Products' %}
                    </div>
                    <div class="boxed-content group">
                        {% product_list search_recs 'Recommended For You' %}
                    </div>


                    <div class="call-to-action-two group">
                        <div class="incipit">
                            <p class="special-font">
                                <span style="font-size:52px;"><strong>35% </strong></span> <span style="font-size:48px;">off everything </span>  Sign in to our list before march 21 to enjoy our special sales!<br />
                            </p>
                        </div>
                        <a href="#" class="call-button">
                        SIGN IN NOW		
                        </a>
                    </div>
                </div>
            </div>
            <!-- END CONTENT -->
        </div>
        <!-- START EXTRA CONTENT -->
        <!-- END EXTRA CONTENT -->    
    </div>
    <!-- END PRIMARY SECTION -->
    {% endblock %}
        

ecomstore/templates/catalog/product.html
{% extends "base.html"%}
{% load catalog_tags %}
{% load catalog_filters %}
{% load staticfiles %}
    {% block extra_title %}{{ page_title }}{% endblock %}
    {% block body_content %}
    
	<!-- START PRIMARY SECTION -->
	<div id="primary" class="inner group" />
	<div class="layout-sidebar-no group">
	   <div id="container">
	      <div id="content" role="main">
	         
	         <div id="breadcrumb">
	            <a class="home" href="home.html">Home</a>  &rsaquo; 
	            <a href="{{ c.get_absolute_url }}">Categories</a> &rsaquo;{{ p.name}}
	        </div>
	         
	         <div class="product type-product status-publish hentry">
	            
	            <div class="images">
	                <a href="{{ p.get_absolute_url }}" class="zoom" rel="prettyphoto[gallery]">
	                    <img width="530" height="345" src="http://127.0.0.1:8000/media/{{p.image}}" class="attachment-530x345 wp-post-image" alt="originalparquet_001_big" title="originalparquet_001_big" />
	                </a>
	               
	                {% include 'tags/product_thumbnail.html' %}
	                <span class="onsale">Sale!</span>
	            </div>
	            <div class="summary">
	               <h1 class="product_title page-title">{{ p.name }}</h1>
					{% if p.sale_price %}
	               <p class="price"><del>{{ p.old_price|currency }}</del> <ins>{{ p.price|currency }}</ins></p>
	               {% else %}
	               <p class="price"><ins>{{ p.price|currency }}</ins></p>
	               {% endif %}
	               <p>
	                  {{ p.description }} 
	                </p>
	               <form action="." class="cart" method="post">
	                  {{ form.as_p }} {% csrf_token %}
	                  <button type="submit" class="button-alt">Add to cart</button>		
	               </form>
	               <div class="product_meta"><span class="sku">SKU:{{ p.sku }}.</span> <span class="posted_in">Posted in <div id="tags">{% for tag in p.tags %}
								{% include 'catalog/tag_link.html' %}
							{% endfor %}</div></span></div>
	               <div class="cb"><br /><br /></div>
						<br />
						{% if request.user.is_authenticated %}
							<label for="id_tag">Tag this product (must be at least three
						characters):</label>
							<br />
							<input id="id_tag" type="text" />
							<input type="submit" value="Tag It" id="add_tag" />
						{% else %}
							<a href="{% url 'login' %}?next={{ request.path }}">
								Log in to tag this product.
							</a>
						{% endif %}
						<div class="cb"><br /><br /></div>
	            </div>
	            <div id="product-tabs">
	               <ul class="tabs">
	                  <li class="active"><a href="#related-products">Related Products</a></li>
	                  <li><a href="#tab-description">Description</a></li>
	                  <li><a href="#tab-reviews">Reviews</a></li>
	               </ul>
	               <div class="containers">
	                  <div class="panel" id="related-products">
	                     <div class="related products">
	                        <ul class="products">
	                        {% for p in p.cross_sell_hybrid %}
								{% include 'tags/product_thumbnail.html' %}
							{% empty %}
								No related products.
							{% endfor %}
	                        </ul>
	                        <div class="clear"></div>
	                     </div>
	                  </div>
	                  <div class="panel" id="tab-description">
	                     {{ p.description }}
	                  </div>
	                  <div class="panel" id="tab-attributes">
	                     <h2>Additional Information</h2>
	                  </div>
	                  <div class="panel" id="tab-reviews">
	                  	<div class="cb"><br /><br /></div>
							<h3>Product Reviews</h3>
							{% if request.user.is_authenticated %}
								<a id="add_review">Write a Review</a>
								<div id="review_form"  >
									<div id="review_errors"></div>
									<table>{% csrf_token %}
										{{ review_form.as_table }}
										<tr><td colspan="2">
											<input type="hidden" id="id_slug" value="{{ p.slug }}" />
											<input type="submit" id="submit_review" value="Submit" />
											<input type="submit" id="cancel_review" value="Cancel" />
										</td></tr>
									</table>
                  				</div>
                  			{% else %}
								<a href="{% url 'login' %}?next={{ request.path }}">
								Log in to write your own review.
								</a>
							{% endif %}
							<div class="cb"><br /><br /></div>
								<div id="reviews">
								{% for review in product_reviews %}
									{% include 'catalog/product_review.html' %}
								{% empty %}
									<div id="no_reviews">
									No product reviews yet.
									</div>
								{% endfor %}
							</div>
						<div class="cb"><br /><br /></div>	
	               	</div>
	            </div>
	         </div>
	      </div>
	   </div>
	</div>
	{% endblock %}

ecomstore/templates/catalog/product_review.html
<div class="review">
	Rating: {{ review.rating }}<br/>
	<strong>{{ review.title }}</strong>  by {{ review.user.username }}
	<br />
	{{ review.content }}
	<br /><br />
	<hr />
</div>

ecomstore/templates/catalog/tag.html
{% extends "base.html"%}
{% load staticfiles %}
{% block extra_title %}{{ page_title }}{% endblock %}
    {% block body_content %}
    	<h1>Products tagged with: '{{ tag }}'</h1>
		{% for p in products %}
			{% include 'tags/product_thumbnail.html' %}
		{% endfor %}
	{% endblock %}

ecomstore/templates/catalog/tag_cloud.html
{% extends "base.html"%}
{% load staticfiles %}
{% load tagging_tags %}
    {% block extra_title %}{{ page_title }}{% endblock %}
    {% block body_content %}
    	<h1>Product Tag Cloud</h1>
			{% for tag in product_tags %}
				<a href="/tag/{{ tag.name }}/" style="font-size:
				{{ tag.font_size|add:"11" }}px;">{{ tag.name|slugify }}</a>&nbsp;
			{% endfor %}
	{% endblock %}

ecomstore/templates/catalog/tag_link.html
<a href="/tag/{{ tag.name }}/" rel="tag">{{ tag.name|slugify }}</a>&nbsp;